spring.application.name=Zpowere
#server.port=8081


#use this for local ennvironment
#spring.datasource.url=jdbc:mysql://localhost:3306/zpower_db
#spring.datasource.username=root
#spring.datasource.password=tarufkhan

# Localhost ki jagah yeuse karein Windows Docker Desktop ke liye
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/zpower_db
#spring.datasource.username=root
#spring.datasource.password=tarufkhan

# Render/Live Configuration

# Wapas variables par aa jao (GitHub block nahi karega)
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

# Baki settings as-is
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection fixes
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5