spring.application.name=Zpowere

#spring.datasource.url=jdbc:mysql://localhost:3306/zpower_d
# Localhost ki jagah ye use karein Windows Docker Desktop ke liye
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/zpower_db
spring.datasource.username=root
spring.datasource.password=tarufkhan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true